filebeat.inputs:
#####################################################
## docker  log
#####################################################
- type: docker
  enabled: true
  containers.ids:
    - '*'
  json.key_under_root: true
  json.overwrite_keys: true
  tags: ["docker"]
  fields:
    tag: docker               #指定标签  在logstahs中可通过[fields][tag]识别

output.logstash:
  hosts: ["logstash:5044"]