filebeat.inputs:
#####################################################
## docker  log
#####################################################
- type: docker
  enabled: true
  containers.ids:
    - '*'
  json.key_under_root: true
  json.overwrite_keys: true
  tags: ["docker"]

output.logstash:
  hosts: ["logstash:5044"]