version: '3'
services:
  tomcat001:
    image: tomcat:7.0.64
    privileged: true
    volumes:
    - ./web/tomcat/ROOT:/usr/local/tomcat/webapps/ROOT
    - ./web/tomcat/conf/1/server.xml:/usr/local/tomcat/conf/server.xml
    - ./log/tomcat1:/usr/local/tomcat/logs
    ports:
    - "8111:8111"
    restart: "always"
    container_name: tomcat001
  tomcat002:
    image: tomcat:7.0.64
    privileged: true
    volumes:
    - ./web/tomcat/ROOT:/usr/local/tomcat/webapps/ROOT
    - ./web/tomcat/conf/2/server.xml:/usr/local/tomcat/conf/server.xml
    - ./log/tomcat2:/usr/local/tomcat/logs
    ports:
    - "8222:8222"
    container_name: tomcat002
    restart: "always"
  nginx:
    image: nginx
    privileged: true
    volumes:
    - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./web/tomcat/ROOT:/usr/nginx/tomcat/ROOT
    - ./log/nginx:/var/log/nginx
    ports:
    - "80:80"
    - "443:443"
    links:
    - tomcat001:t01
    - tomcat002:t02
  elasticsearch:
    image: elasticsearch:7.2.0
    privileged: true
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    hostname: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknet
  kibana:
    image: kibana:7.2.0
    privileged: true
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    hostname: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"
    networks:
      - elknet
  logstash:
    image: docker.io/elastic/logstash:7.2.0
    privileged: true
    hostname: logstash
    restart: always
    depends_on:
      - kibana
    links:
      - elasticsearch
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
    - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/conf.d/:/usr/share/logstash/conf.d/
    networks:
      - elknet
  filebeat:
    image: docker.io/elastic/filebeat:7.2.0
    privileged: true
    hostname: filebeat
    restart: always
    depends_on:
      - logstash
    links:
      - logstash
    volumes:
    - ./log/:/var/log/
    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elknet
networks:
  elknet: